// Generated by gencpp from file radar_conti/ClusterList.msg
// DO NOT EDIT!


#ifndef RADAR_CONTI_MESSAGE_CLUSTERLIST_H
#define RADAR_CONTI_MESSAGE_CLUSTERLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Int32.h>
#include <radar_conti/Cluster.h>

namespace radar_conti
{
template <class ContainerAllocator>
struct ClusterList_
{
  typedef ClusterList_<ContainerAllocator> Type;

  ClusterList_()
    : header()
    , cluster_count()
    , clusters()  {
    }
  ClusterList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cluster_count(_alloc)
    , clusters(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _cluster_count_type;
  _cluster_count_type cluster_count;

   typedef std::vector< ::radar_conti::Cluster_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::radar_conti::Cluster_<ContainerAllocator> >> _clusters_type;
  _clusters_type clusters;





  typedef boost::shared_ptr< ::radar_conti::ClusterList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_conti::ClusterList_<ContainerAllocator> const> ConstPtr;

}; // struct ClusterList_

typedef ::radar_conti::ClusterList_<std::allocator<void> > ClusterList;

typedef boost::shared_ptr< ::radar_conti::ClusterList > ClusterListPtr;
typedef boost::shared_ptr< ::radar_conti::ClusterList const> ClusterListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_conti::ClusterList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_conti::ClusterList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_conti::ClusterList_<ContainerAllocator1> & lhs, const ::radar_conti::ClusterList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cluster_count == rhs.cluster_count &&
    lhs.clusters == rhs.clusters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_conti::ClusterList_<ContainerAllocator1> & lhs, const ::radar_conti::ClusterList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_conti

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_conti::ClusterList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_conti::ClusterList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_conti::ClusterList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_conti::ClusterList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_conti::ClusterList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_conti::ClusterList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_conti::ClusterList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f224f52f8435f121b949e6b05d35dc26";
  }

  static const char* value(const ::radar_conti::ClusterList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf224f52f8435f121ULL;
  static const uint64_t static_value2 = 0xb949e6b05d35dc26ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_conti::ClusterList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_conti/ClusterList";
  }

  static const char* value(const ::radar_conti::ClusterList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_conti::ClusterList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Int32 cluster_count\n"
"Cluster[] clusters\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
"================================================================================\n"
"MSG: radar_conti/Cluster\n"
"std_msgs/Int32 cluster_id\n"
"ClusterGeneral cluster_general\n"
"ClusterQuality cluster_quality\n"
"================================================================================\n"
"MSG: radar_conti/ClusterGeneral\n"
"#  ------------------------------------------------------------------------\n"
"#\n"
"#  Name:       Cluster_1_General\n"
"#  Id:         0x701\n"
"#  Length:     8 bytes\n"
"#  Cycle time: 0 ms\n"
"#  Senders:    ARS_ISF\n"
"#  Layout:\n"
"#\n"
"#                          Bit\n"
"#\n"
"#             7   6   5   4   3   2   1   0\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         0 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Cluster_ID\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         1 |<------------------------------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         2 |------------------x|   |<------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                             +-- Cluster_DistLong\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         3 |------------------------------x|\n"
"#     B     +---+---+---+---+---+---+---+---+\n"
"#     y                                   +-- Cluster_DistLat\n"
"#     t     +---+---+---+---+---+---+---+---+\n"
"#     e   4 |<------------------------------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         5 |------x|<----------------------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                 +-- Cluster_VrelLong\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         6 |----------x|   |   |<---------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                     |                   +-- Cluster_DynProp\n"
"#                     +-- Cluster_VrelLat\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         7 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Cluster_RCS\n"
"#\n"
"#  Signal tree:\n"
"#\n"
"#    -- {root}\n"
"#       +-- Cluster_ID\n"
"#       +-- Cluster_DistLong\n"
"#       +-- Cluster_DistLat\n"
"#       +-- Cluster_VrelLong\n"
"#       +-- Cluster_VrelLat\n"
"#       +-- Cluster_DynProp\n"
"#       +-- Cluster_RCS\n"
"#\n"
"#  ------------------------------------------------------------------------\n"
"std_msgs/Float64 cluster_distlong\n"
"std_msgs/Float64 cluster_distlat\n"
"std_msgs/Float64 cluster_vrellong\n"
"std_msgs/Float64 cluster_vrellat\n"
"std_msgs/Int32   cluster_dynprop\n"
"std_msgs/Float64 cluster_rcs\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: radar_conti/ClusterQuality\n"
"#  ------------------------------------------------------------------------\n"
"#\n"
"#  Name:       Cluster_2_Quality\n"
"#  Id:         0x702\n"
"#  Length:     5 bytes\n"
"#  Cycle time: 0 ms\n"
"#  Senders:    ARS_ISF\n"
"#  Layout:\n"
"#\n"
"#                          Bit\n"
"#\n"
"#             7   6   5   4   3   2   1   0\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         0 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Cluster_ID\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         1 |<-----------------x|<----------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                             +-- Cluster_DistLong_rms\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#     B   2 |------x|<-----------------x|<--|\n"
"#     y     +---+---+---+---+---+---+---+---+\n"
"#     t           |                   +-- Cluster_VrelLong_rms\n"
"#     e           +-- Cluster_DistLat_rms\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         3 |--------------x|   |<---------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                         |               +-- Cluster_PdH0\n"
"#                         +-- Cluster_VrelLat_rms\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         4 |<-----------------x|<---------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                             |           +-- Cluster_AmbigState\n"
"#                             +-- Cluster_InvalidState\n"
"#\n"
"#  Signal tree:\n"
"#\n"
"#    -- {root}\n"
"#       +-- Cluster_ID\n"
"#       +-- Cluster_DistLong_rms\n"
"#       +-- Cluster_DistLat_rms\n"
"#       +-- Cluster_VrelLong_rms\n"
"#       +-- Cluster_VrelLat_rms\n"
"#       +-- Cluster_PdH0\n"
"#       +-- Cluster_InvalidState\n"
"#       +-- Cluster_AmbigState\n"
"#\n"
"#  ------------------------------------------------------------------------\n"
"#\n"
"std_msgs/Float64 cluster_distlong_rms\n"
"std_msgs/Float64 cluster_distlat_rms\n"
"std_msgs/Float64 cluster_vrellong_rms\n"
"std_msgs/Float64 cluster_vrellat_rms\n"
"std_msgs/String cluster_pdh0\n"
"std_msgs/String cluster_invalidstate\n"
"std_msgs/String cluster_ambigstate\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::radar_conti::ClusterList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_conti::ClusterList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cluster_count);
      stream.next(m.clusters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClusterList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_conti::ClusterList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_conti::ClusterList_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cluster_count: ";
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.cluster_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "clusters: ";
    if (v.clusters.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.clusters.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::radar_conti::Cluster_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.clusters[i]);
    }
    if (v.clusters.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_CONTI_MESSAGE_CLUSTERLIST_H
