// Generated by gencpp from file radar_conti/ClusterStatus.msg
// DO NOT EDIT!


#ifndef RADAR_CONTI_MESSAGE_CLUSTERSTATUS_H
#define RADAR_CONTI_MESSAGE_CLUSTERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Int32.h>

namespace radar_conti
{
template <class ContainerAllocator>
struct ClusterStatus_
{
  typedef ClusterStatus_<ContainerAllocator> Type;

  ClusterStatus_()
    : cluster_nofclustersnear()
    , cluster_nofclustersfar()
    , cluster_meascounter()
    , cluster_interfaceversion()  {
    }
  ClusterStatus_(const ContainerAllocator& _alloc)
    : cluster_nofclustersnear(_alloc)
    , cluster_nofclustersfar(_alloc)
    , cluster_meascounter(_alloc)
    , cluster_interfaceversion(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _cluster_nofclustersnear_type;
  _cluster_nofclustersnear_type cluster_nofclustersnear;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _cluster_nofclustersfar_type;
  _cluster_nofclustersfar_type cluster_nofclustersfar;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _cluster_meascounter_type;
  _cluster_meascounter_type cluster_meascounter;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _cluster_interfaceversion_type;
  _cluster_interfaceversion_type cluster_interfaceversion;





  typedef boost::shared_ptr< ::radar_conti::ClusterStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_conti::ClusterStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ClusterStatus_

typedef ::radar_conti::ClusterStatus_<std::allocator<void> > ClusterStatus;

typedef boost::shared_ptr< ::radar_conti::ClusterStatus > ClusterStatusPtr;
typedef boost::shared_ptr< ::radar_conti::ClusterStatus const> ClusterStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_conti::ClusterStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_conti::ClusterStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_conti::ClusterStatus_<ContainerAllocator1> & lhs, const ::radar_conti::ClusterStatus_<ContainerAllocator2> & rhs)
{
  return lhs.cluster_nofclustersnear == rhs.cluster_nofclustersnear &&
    lhs.cluster_nofclustersfar == rhs.cluster_nofclustersfar &&
    lhs.cluster_meascounter == rhs.cluster_meascounter &&
    lhs.cluster_interfaceversion == rhs.cluster_interfaceversion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_conti::ClusterStatus_<ContainerAllocator1> & lhs, const ::radar_conti::ClusterStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_conti

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_conti::ClusterStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_conti::ClusterStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_conti::ClusterStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_conti::ClusterStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_conti::ClusterStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_conti::ClusterStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_conti::ClusterStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f2a6f691f628cc21b647de1bb56d9b7";
  }

  static const char* value(const ::radar_conti::ClusterStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f2a6f691f628cc2ULL;
  static const uint64_t static_value2 = 0x1b647de1bb56d9b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_conti::ClusterStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_conti/ClusterStatus";
  }

  static const char* value(const ::radar_conti::ClusterStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_conti::ClusterStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#  ------------------------------------------------------------------------\n"
"#\n"
"#  Name:       Cluster_0_Status\n"
"#  Id:         0x600\n"
"#  Length:     5 bytes\n"
"#  Cycle time: 0 ms\n"
"#  Senders:    ARS_ISF\n"
"#  Layout:\n"
"#\n"
"#                          Bit\n"
"#\n"
"#             7   6   5   4   3   2   1   0\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         0 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Cluster_NofClustersNear\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         1 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#     B                                   +-- Cluster_NofClustersFar\n"
"#     y     +---+---+---+---+---+---+---+---+\n"
"#     t   2 |<------------------------------|\n"
"#     e     +---+---+---+---+---+---+---+---+\n"
"#         3 |------------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Cluster_MeasCounter\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         4 |<-------------x|   |   |   |   |\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                         +-- Cluster_InterfaceVersion\n"
"#\n"
"#  Signal tree:\n"
"#\n"
"#    -- {root}\n"
"#       +-- Cluster_NofClustersNear\n"
"#       +-- Cluster_NofClustersFar\n"
"#       +-- Cluster_MeasCounter\n"
"#       +-- Cluster_InterfaceVersion\n"
"#\n"
"#  ------------------------------------------------------------------------\n"
"#\n"
"std_msgs/Int32 cluster_nofclustersnear\n"
"std_msgs/Int32 cluster_nofclustersfar\n"
"std_msgs/Int32 cluster_meascounter\n"
"std_msgs/Int32 cluster_interfaceversion\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
;
  }

  static const char* value(const ::radar_conti::ClusterStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_conti::ClusterStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cluster_nofclustersnear);
      stream.next(m.cluster_nofclustersfar);
      stream.next(m.cluster_meascounter);
      stream.next(m.cluster_interfaceversion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClusterStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_conti::ClusterStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_conti::ClusterStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cluster_nofclustersnear: ";
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.cluster_nofclustersnear);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cluster_nofclustersfar: ";
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.cluster_nofclustersfar);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cluster_meascounter: ";
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.cluster_meascounter);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cluster_interfaceversion: ";
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.cluster_interfaceversion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_CONTI_MESSAGE_CLUSTERSTATUS_H
