// Generated by gencpp from file radar_conti/CollisonObj.msg
// DO NOT EDIT!


#ifndef RADAR_CONTI_MESSAGE_COLLISONOBJ_H
#define RADAR_CONTI_MESSAGE_COLLISONOBJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>

namespace radar_conti
{
template <class ContainerAllocator>
struct CollisonObj_
{
  typedef CollisonObj_<ContainerAllocator> Type;

  CollisonObj_()
    : obj_id()  {
    }
  CollisonObj_(const ContainerAllocator& _alloc)
    : obj_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _obj_id_type;
  _obj_id_type obj_id;





  typedef boost::shared_ptr< ::radar_conti::CollisonObj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_conti::CollisonObj_<ContainerAllocator> const> ConstPtr;

}; // struct CollisonObj_

typedef ::radar_conti::CollisonObj_<std::allocator<void> > CollisonObj;

typedef boost::shared_ptr< ::radar_conti::CollisonObj > CollisonObjPtr;
typedef boost::shared_ptr< ::radar_conti::CollisonObj const> CollisonObjConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_conti::CollisonObj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_conti::CollisonObj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_conti::CollisonObj_<ContainerAllocator1> & lhs, const ::radar_conti::CollisonObj_<ContainerAllocator2> & rhs)
{
  return lhs.obj_id == rhs.obj_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_conti::CollisonObj_<ContainerAllocator1> & lhs, const ::radar_conti::CollisonObj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_conti

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_conti::CollisonObj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_conti::CollisonObj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_conti::CollisonObj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_conti::CollisonObj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_conti::CollisonObj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_conti::CollisonObj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_conti::CollisonObj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0bbbfa30045347256b800ec4412e538";
  }

  static const char* value(const ::radar_conti::CollisonObj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0bbbfa300453472ULL;
  static const uint64_t static_value2 = 0x56b800ec4412e538ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_conti::CollisonObj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_conti/CollisonObj";
  }

  static const char* value(const ::radar_conti::CollisonObj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_conti::CollisonObj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32 obj_id\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
;
  }

  static const char* value(const ::radar_conti::CollisonObj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_conti::CollisonObj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obj_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollisonObj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_conti::CollisonObj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_conti::CollisonObj_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "obj_id: ";
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.obj_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_CONTI_MESSAGE_COLLISONOBJ_H
