// Generated by gencpp from file radar_conti/ObjectList.msg
// DO NOT EDIT!


#ifndef RADAR_CONTI_MESSAGE_OBJECTLIST_H
#define RADAR_CONTI_MESSAGE_OBJECTLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Int32.h>
#include <radar_conti/Object.h>

namespace radar_conti
{
template <class ContainerAllocator>
struct ObjectList_
{
  typedef ObjectList_<ContainerAllocator> Type;

  ObjectList_()
    : header()
    , object_count()
    , objects()  {
    }
  ObjectList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_count(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _object_count_type;
  _object_count_type object_count;

   typedef std::vector< ::radar_conti::Object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::radar_conti::Object_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::radar_conti::ObjectList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_conti::ObjectList_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectList_

typedef ::radar_conti::ObjectList_<std::allocator<void> > ObjectList;

typedef boost::shared_ptr< ::radar_conti::ObjectList > ObjectListPtr;
typedef boost::shared_ptr< ::radar_conti::ObjectList const> ObjectListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_conti::ObjectList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_conti::ObjectList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_conti::ObjectList_<ContainerAllocator1> & lhs, const ::radar_conti::ObjectList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_count == rhs.object_count &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_conti::ObjectList_<ContainerAllocator1> & lhs, const ::radar_conti::ObjectList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_conti

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_conti::ObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_conti::ObjectList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_conti::ObjectList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_conti::ObjectList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_conti::ObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_conti::ObjectList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_conti::ObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7dbccc0809b5bdaa59e6da1bf9289de";
  }

  static const char* value(const ::radar_conti::ObjectList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7dbccc0809b5bdaULL;
  static const uint64_t static_value2 = 0xa59e6da1bf9289deULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_conti::ObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_conti/ObjectList";
  }

  static const char* value(const ::radar_conti::ObjectList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_conti::ObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Int32 object_count\n"
"Object[] objects\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
"================================================================================\n"
"MSG: radar_conti/Object\n"
"std_msgs/Int32 obj_id\n"
"ObjectGeneral object_general\n"
"ObjectExtended object_extended\n"
"ObjectQuality object_quality\n"
"================================================================================\n"
"MSG: radar_conti/ObjectGeneral\n"
"#  ------------------------------------------------------------------------\n"
"#\n"
"#  Name:       Obj_1_General\n"
"#  Id:         0x60b\n"
"#  Length:     8 bytes\n"
"#  Cycle time: 0 ms\n"
"#  Senders:    ARS_ISF\n"
"#  Layout:\n"
"#\n"
"#                          Bit\n"
"#\n"
"#             7   6   5   4   3   2   1   0\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         0 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Obj_ID\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         1 |<------------------------------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         2 |------------------x|<----------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                             +-- Obj_DistLong\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         3 |------------------------------x|\n"
"#     B     +---+---+---+---+---+---+---+---+\n"
"#     y                                   +-- Obj_DistLat\n"
"#     t     +---+---+---+---+---+---+---+---+\n"
"#     e   4 |<------------------------------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         5 |------x|<----------------------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                 +-- Obj_VrelLong\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         6 |----------x|   |   |<---------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                     |                   +-- Obj_DynProp\n"
"#                     +-- Obj_VrelLat\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         7 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Obj_RCS\n"
"#\n"
"#  Signal tree:\n"
"#\n"
"#    -- {root}\n"
"#       +-- Obj_ID\n"
"#       +-- Obj_DistLong\n"
"#       +-- Obj_DistLat\n"
"#       +-- Obj_VrelLong\n"
"#       +-- Obj_VrelLat\n"
"#       +-- Obj_DynProp\n"
"#       +-- Obj_RCS\n"
"#\n"
"#  ------------------------------------------------------------------------\n"
"#\n"
"std_msgs/Float64 obj_distlong\n"
"std_msgs/Float64 obj_distlat\n"
"std_msgs/Float64 obj_vrellong\n"
"std_msgs/Float64 obj_vrellat\n"
"std_msgs/String obj_dynprop\n"
"std_msgs/Float64 obj_rcs\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: radar_conti/ObjectExtended\n"
"#  ------------------------------------------------------------------------\n"
"#\n"
"#  Name:       Obj_3_Extended\n"
"#  Id:         0x60d\n"
"#  Length:     8 bytes\n"
"#  Cycle time: 0 ms\n"
"#  Senders:    ARS_ISF\n"
"#  Layout:\n"
"#\n"
"#                          Bit\n"
"#\n"
"#             7   6   5   4   3   2   1   0\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         0 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Obj_ID\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         1 |<------------------------------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         2 |----------x|<------------------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                     +-- Obj_ArelLong\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         3 |--------------x|   |<---------x|\n"
"#     B     +---+---+---+---+---+---+---+---+\n"
"#     y                   |               +-- Obj_Class\n"
"#     t                   +-- Obj_ArelLat\n"
"#     e     +---+---+---+---+---+---+---+---+\n"
"#         4 |<------------------------------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         5 |------x|   |   |   |   |   |   |\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                 +-- Obj_OrientationAngle\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         6 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Obj_Length\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         7 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Obj_Width\n"
"#\n"
"#  Signal tree:\n"
"#\n"
"#    -- {root}\n"
"#       +-- Obj_ID\n"
"#       +-- Obj_ArelLong\n"
"#       +-- Obj_ArelLat\n"
"#       +-- Obj_Class\n"
"#       +-- Obj_OrientationAngle\n"
"#       +-- Obj_Length\n"
"#       +-- Obj_Width\n"
"#\n"
"#  ------------------------------------------------------------------------\n"
"#\n"
"std_msgs/Float64 obj_arellong\n"
"std_msgs/Float64 obj_arellat\n"
"std_msgs/Int32 obj_class\n"
"std_msgs/Float64 obj_orientationangle\n"
"std_msgs/Float64 obj_length\n"
"std_msgs/Float64 obj_width\n"
"================================================================================\n"
"MSG: radar_conti/ObjectQuality\n"
"#  ------------------------------------------------------------------------\n"
"#\n"
"#  Name:       Obj_2_Quality\n"
"#  Id:         0x60c\n"
"#  Length:     7 bytes\n"
"#  Cycle time: 0 ms\n"
"#  Senders:    ARS_ISF\n"
"#  Layout:\n"
"#\n"
"#                          Bit\n"
"#\n"
"#             7   6   5   4   3   2   1   0\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         0 |<-----------------------------x|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                                         +-- Obj_ID\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         1 |<-----------------x|<----------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                             +-- Obj_DistLong_rms\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         2 |------x|<-----------------x|<--|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                 |                   +-- Obj_VrelLong_rms\n"
"#                 +-- Obj_DistLat_rms\n"
"#     B     +---+---+---+---+---+---+---+---+\n"
"#     y   3 |--------------x|<--------------|\n"
"#     t     +---+---+---+---+---+---+---+---+\n"
"#     e                   +-- Obj_VrelLat_rms\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         4 |--x|<-----------------x|<------|\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#             |                   +-- Obj_ArelLat_rms\n"
"#             +-- Obj_ArelLong_rms\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         5 |----------x|   |   |   |   |   |\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                     +-- Obj_Orientation_rms\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#         6 |<---------x|<---------x|   |   |\n"
"#           +---+---+---+---+---+---+---+---+\n"
"#                     |           +-- Obj_MeasState\n"
"#                     +-- Obj_ProbOfExist\n"
"#\n"
"#  Signal tree:\n"
"#\n"
"#    -- {root}\n"
"#       +-- Obj_ID\n"
"#       +-- Obj_DistLong_rms\n"
"#       +-- Obj_DistLat_rms\n"
"#       +-- Obj_VrelLong_rms\n"
"#       +-- Obj_VrelLat_rms\n"
"#       +-- Obj_ArelLong_rms\n"
"#       +-- Obj_ArelLat_rms\n"
"#       +-- Obj_Orientation_rms\n"
"#       +-- Obj_ProbOfExist\n"
"#       +-- Obj_MeasState\n"
"#\n"
"#  ------------------------------------------------------------------------\n"
"std_msgs/Float64 obj_distlong_rms\n"
"std_msgs/Float64 obj_distlat_rms\n"
"std_msgs/Float64 obj_vrellong_rms\n"
"std_msgs/Float64 obj_vrellat_rms\n"
"std_msgs/Float64 obj_arellong_rms\n"
"std_msgs/Float64 obj_arellat_rms\n"
"std_msgs/Float64 obj_orientation_rms\n"
"std_msgs/Float64 obj_probofexist\n"
"std_msgs/String  obj_measstate\n"
;
  }

  static const char* value(const ::radar_conti::ObjectList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_conti::ObjectList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_count);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_conti::ObjectList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_conti::ObjectList_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_count: ";
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.object_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::radar_conti::Object_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_CONTI_MESSAGE_OBJECTLIST_H
