// Generated by gencpp from file npust_bus_msgs/LanePolynomial.msg
// DO NOT EDIT!


#ifndef NPUST_BUS_MSGS_MESSAGE_LANEPOLYNOMIAL_H
#define NPUST_BUS_MSGS_MESSAGE_LANEPOLYNOMIAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace npust_bus_msgs
{
template <class ContainerAllocator>
struct LanePolynomial_
{
  typedef LanePolynomial_<ContainerAllocator> Type;

  LanePolynomial_()
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , is_valid(false)  {
    }
  LanePolynomial_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , is_valid(false)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;





  typedef boost::shared_ptr< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> const> ConstPtr;

}; // struct LanePolynomial_

typedef ::npust_bus_msgs::LanePolynomial_<std::allocator<void> > LanePolynomial;

typedef boost::shared_ptr< ::npust_bus_msgs::LanePolynomial > LanePolynomialPtr;
typedef boost::shared_ptr< ::npust_bus_msgs::LanePolynomial const> LanePolynomialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::npust_bus_msgs::LanePolynomial_<ContainerAllocator1> & lhs, const ::npust_bus_msgs::LanePolynomial_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.is_valid == rhs.is_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::npust_bus_msgs::LanePolynomial_<ContainerAllocator1> & lhs, const ::npust_bus_msgs::LanePolynomial_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace npust_bus_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d23cdde470f87162ea53865c3a120f7d";
  }

  static const char* value(const ::npust_bus_msgs::LanePolynomial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd23cdde470f87162ULL;
  static const uint64_t static_value2 = 0xea53865c3a120f7dULL;
};

template<class ContainerAllocator>
struct DataType< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "npust_bus_msgs/LanePolynomial";
  }

  static const char* value(const ::npust_bus_msgs::LanePolynomial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# [TEMP SIM] LanePolynomial — second-order lateral lane boundary:\n"
"#   y(x) = a*x^2 + b*x + c\n"
"# Validity gates (from kinematics.cpp / isLaneValid):\n"
"#   is_valid must be true\n"
"#   |a| <= max_lane_curve_a   (default 0.02)\n"
"#   |b| <= max_lane_heading_b (default 0.35)\n"
"float64 a\n"
"float64 b\n"
"float64 c\n"
"bool    is_valid\n"
;
  }

  static const char* value(const ::npust_bus_msgs::LanePolynomial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.is_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LanePolynomial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::npust_bus_msgs::LanePolynomial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::npust_bus_msgs::LanePolynomial_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NPUST_BUS_MSGS_MESSAGE_LANEPOLYNOMIAL_H
