// Generated by gencpp from file npust_bus_msgs/TrackedObject.msg
// DO NOT EDIT!


#ifndef NPUST_BUS_MSGS_MESSAGE_TRACKEDOBJECT_H
#define NPUST_BUS_MSGS_MESSAGE_TRACKEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace npust_bus_msgs
{
template <class ContainerAllocator>
struct TrackedObject_
{
  typedef TrackedObject_<ContainerAllocator> Type;

  TrackedObject_()
    : x(0.0)
    , y(0.0)
    , vx(0.0)
    , id(0)
    , x_var(0.0)
    , y_var(0.0)
    , vx_var(0.0)  {
    }
  TrackedObject_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , vx(0.0)
    , id(0)
    , x_var(0.0)
    , y_var(0.0)
    , vx_var(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _vx_type;
  _vx_type vx;

   typedef int32_t _id_type;
  _id_type id;

   typedef double _x_var_type;
  _x_var_type x_var;

   typedef double _y_var_type;
  _y_var_type y_var;

   typedef double _vx_var_type;
  _vx_var_type vx_var;





  typedef boost::shared_ptr< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObject_

typedef ::npust_bus_msgs::TrackedObject_<std::allocator<void> > TrackedObject;

typedef boost::shared_ptr< ::npust_bus_msgs::TrackedObject > TrackedObjectPtr;
typedef boost::shared_ptr< ::npust_bus_msgs::TrackedObject const> TrackedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::npust_bus_msgs::TrackedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::npust_bus_msgs::TrackedObject_<ContainerAllocator1> & lhs, const ::npust_bus_msgs::TrackedObject_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.vx == rhs.vx &&
    lhs.id == rhs.id &&
    lhs.x_var == rhs.x_var &&
    lhs.y_var == rhs.y_var &&
    lhs.vx_var == rhs.vx_var;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::npust_bus_msgs::TrackedObject_<ContainerAllocator1> & lhs, const ::npust_bus_msgs::TrackedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace npust_bus_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "331682f7f129bb4bca16e4da62c26662";
  }

  static const char* value(const ::npust_bus_msgs::TrackedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x331682f7f129bb4bULL;
  static const uint64_t static_value2 = 0xca16e4da62c26662ULL;
};

template<class ContainerAllocator>
struct DataType< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "npust_bus_msgs/TrackedObject";
  }

  static const char* value(const ::npust_bus_msgs::TrackedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# TrackedObject — single detected object from the perception stack.\n"
"# Fields used by acc_aeb kinematics.cpp:\n"
"#   x      — longitudinal range ahead (m), must be > min_valid_x_m (0.5 m)\n"
"#   y      — lateral offset (m); positive = left\n"
"#   vx     — world-frame absolute velocity when vx_is_relative=false (m/s)\n"
"#             relative-to-ego velocity when vx_is_relative=true (m/s)\n"
"#   id     — stable tracking ID; consistent across frames for the Kalman filter\n"
"#   x_var  — variance of x measurement (m²)\n"
"#   y_var  — variance of y measurement (m²)\n"
"#   vx_var — variance of vx measurement (m²/s²)\n"
"float64 x\n"
"float64 y\n"
"float64 vx\n"
"int32   id\n"
"float64 x_var\n"
"float64 y_var\n"
"float64 vx_var\n"
;
  }

  static const char* value(const ::npust_bus_msgs::TrackedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vx);
      stream.next(m.id);
      stream.next(m.x_var);
      stream.next(m.y_var);
      stream.next(m.vx_var);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::npust_bus_msgs::TrackedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::npust_bus_msgs::TrackedObject_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_var: ";
    Printer<double>::stream(s, indent + "  ", v.x_var);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_var: ";
    Printer<double>::stream(s, indent + "  ", v.y_var);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vx_var: ";
    Printer<double>::stream(s, indent + "  ", v.vx_var);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NPUST_BUS_MSGS_MESSAGE_TRACKEDOBJECT_H
