(cl:in-package radar_conti-msg)
(cl:export '(HEADER-VAL
          HEADER
          VERSION_MAJORRELEASE-VAL
          VERSION_MAJORRELEASE
          VERSION_MINORRELEASE-VAL
          VERSION_MINORRELEASE
          VERSION_PATCHLEVEL-VAL
          VERSION_PATCHLEVEL
          VERSION_EXTENDEDRANGE-VAL
          VERSION_EXTENDEDRANGE
          VERSION_COUNTRYCODE-VAL
          VERSION_COUNTRYCODE
))