(cl:in-package radar_conti-msg)
(cl:export '(CLUSTER_DISTLONG_RMS-VAL
          CLUSTER_DISTLONG_RMS
          CLUSTER_DISTLAT_RMS-VAL
          CLUSTER_DISTLAT_RMS
          CLUSTER_VRELLONG_RMS-VAL
          CLUSTER_VRELLONG_RMS
          CLUSTER_VRELLAT_RMS-VAL
          CLUSTER_VRELLAT_RMS
          CLUSTER_PDH0-VAL
          CLUSTER_PDH0
          CLUSTER_INVALIDSTATE-VAL
          CLUSTER_INVALIDSTATE
          CLUSTER_AMBIGSTATE-VAL
          CLUSTER_AMBIGSTATE
))