(cl:in-package radar_conti-msg)
(cl:export '(CLUSTER_NOFCLUSTERSNEAR-VAL
          CLUSTER_NOFCLUSTERSNEAR
          CLUSTER_NOFCLUSTERSFAR-VAL
          CLUSTER_NOFCLUSTERSFAR
          CLUSTER_MEASCOUNTER-VAL
          CLUSTER_MEASCOUNTER
          CLUSTER_INTERFACEVERSION-VAL
          CLUSTER_INTERFACEVERSION
))