# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_conti/Cluster.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import radar_conti.msg
import std_msgs.msg

class Cluster(genpy.Message):
  _md5sum = "2811095d8cefca700603904d21f118c9"
  _type = "radar_conti/Cluster"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Int32 cluster_id
ClusterGeneral cluster_general
ClusterQuality cluster_quality
================================================================================
MSG: std_msgs/Int32
int32 data
================================================================================
MSG: radar_conti/ClusterGeneral
#  ------------------------------------------------------------------------
#
#  Name:       Cluster_1_General
#  Id:         0x701
#  Length:     8 bytes
#  Cycle time: 0 ms
#  Senders:    ARS_ISF
#  Layout:
#
#                          Bit
#
#             7   6   5   4   3   2   1   0
#           +---+---+---+---+---+---+---+---+
#         0 |<-----------------------------x|
#           +---+---+---+---+---+---+---+---+
#                                         +-- Cluster_ID
#           +---+---+---+---+---+---+---+---+
#         1 |<------------------------------|
#           +---+---+---+---+---+---+---+---+
#         2 |------------------x|   |<------|
#           +---+---+---+---+---+---+---+---+
#                             +-- Cluster_DistLong
#           +---+---+---+---+---+---+---+---+
#         3 |------------------------------x|
#     B     +---+---+---+---+---+---+---+---+
#     y                                   +-- Cluster_DistLat
#     t     +---+---+---+---+---+---+---+---+
#     e   4 |<------------------------------|
#           +---+---+---+---+---+---+---+---+
#         5 |------x|<----------------------|
#           +---+---+---+---+---+---+---+---+
#                 +-- Cluster_VrelLong
#           +---+---+---+---+---+---+---+---+
#         6 |----------x|   |   |<---------x|
#           +---+---+---+---+---+---+---+---+
#                     |                   +-- Cluster_DynProp
#                     +-- Cluster_VrelLat
#           +---+---+---+---+---+---+---+---+
#         7 |<-----------------------------x|
#           +---+---+---+---+---+---+---+---+
#                                         +-- Cluster_RCS
#
#  Signal tree:
#
#    -- {root}
#       +-- Cluster_ID
#       +-- Cluster_DistLong
#       +-- Cluster_DistLat
#       +-- Cluster_VrelLong
#       +-- Cluster_VrelLat
#       +-- Cluster_DynProp
#       +-- Cluster_RCS
#
#  ------------------------------------------------------------------------
std_msgs/Float64 cluster_distlong
std_msgs/Float64 cluster_distlat
std_msgs/Float64 cluster_vrellong
std_msgs/Float64 cluster_vrellat
std_msgs/Int32   cluster_dynprop
std_msgs/Float64 cluster_rcs
================================================================================
MSG: std_msgs/Float64
float64 data
================================================================================
MSG: radar_conti/ClusterQuality
#  ------------------------------------------------------------------------
#
#  Name:       Cluster_2_Quality
#  Id:         0x702
#  Length:     5 bytes
#  Cycle time: 0 ms
#  Senders:    ARS_ISF
#  Layout:
#
#                          Bit
#
#             7   6   5   4   3   2   1   0
#           +---+---+---+---+---+---+---+---+
#         0 |<-----------------------------x|
#           +---+---+---+---+---+---+---+---+
#                                         +-- Cluster_ID
#           +---+---+---+---+---+---+---+---+
#         1 |<-----------------x|<----------|
#           +---+---+---+---+---+---+---+---+
#                             +-- Cluster_DistLong_rms
#           +---+---+---+---+---+---+---+---+
#     B   2 |------x|<-----------------x|<--|
#     y     +---+---+---+---+---+---+---+---+
#     t           |                   +-- Cluster_VrelLong_rms
#     e           +-- Cluster_DistLat_rms
#           +---+---+---+---+---+---+---+---+
#         3 |--------------x|   |<---------x|
#           +---+---+---+---+---+---+---+---+
#                         |               +-- Cluster_PdH0
#                         +-- Cluster_VrelLat_rms
#           +---+---+---+---+---+---+---+---+
#         4 |<-----------------x|<---------x|
#           +---+---+---+---+---+---+---+---+
#                             |           +-- Cluster_AmbigState
#                             +-- Cluster_InvalidState
#
#  Signal tree:
#
#    -- {root}
#       +-- Cluster_ID
#       +-- Cluster_DistLong_rms
#       +-- Cluster_DistLat_rms
#       +-- Cluster_VrelLong_rms
#       +-- Cluster_VrelLat_rms
#       +-- Cluster_PdH0
#       +-- Cluster_InvalidState
#       +-- Cluster_AmbigState
#
#  ------------------------------------------------------------------------
#
std_msgs/Float64 cluster_distlong_rms
std_msgs/Float64 cluster_distlat_rms
std_msgs/Float64 cluster_vrellong_rms
std_msgs/Float64 cluster_vrellat_rms
std_msgs/String cluster_pdh0
std_msgs/String cluster_invalidstate
std_msgs/String cluster_ambigstate
================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['cluster_id','cluster_general','cluster_quality']
  _slot_types = ['std_msgs/Int32','radar_conti/ClusterGeneral','radar_conti/ClusterQuality']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cluster_id,cluster_general,cluster_quality

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Cluster, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cluster_id is None:
        self.cluster_id = std_msgs.msg.Int32()
      if self.cluster_general is None:
        self.cluster_general = radar_conti.msg.ClusterGeneral()
      if self.cluster_quality is None:
        self.cluster_quality = radar_conti.msg.ClusterQuality()
    else:
      self.cluster_id = std_msgs.msg.Int32()
      self.cluster_general = radar_conti.msg.ClusterGeneral()
      self.cluster_quality = radar_conti.msg.ClusterQuality()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i4di5d().pack(_x.cluster_id.data, _x.cluster_general.cluster_distlong.data, _x.cluster_general.cluster_distlat.data, _x.cluster_general.cluster_vrellong.data, _x.cluster_general.cluster_vrellat.data, _x.cluster_general.cluster_dynprop.data, _x.cluster_general.cluster_rcs.data, _x.cluster_quality.cluster_distlong_rms.data, _x.cluster_quality.cluster_distlat_rms.data, _x.cluster_quality.cluster_vrellong_rms.data, _x.cluster_quality.cluster_vrellat_rms.data))
      _x = self.cluster_quality.cluster_pdh0.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cluster_quality.cluster_invalidstate.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cluster_quality.cluster_ambigstate.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cluster_id is None:
        self.cluster_id = std_msgs.msg.Int32()
      if self.cluster_general is None:
        self.cluster_general = radar_conti.msg.ClusterGeneral()
      if self.cluster_quality is None:
        self.cluster_quality = radar_conti.msg.ClusterQuality()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.cluster_id.data, _x.cluster_general.cluster_distlong.data, _x.cluster_general.cluster_distlat.data, _x.cluster_general.cluster_vrellong.data, _x.cluster_general.cluster_vrellat.data, _x.cluster_general.cluster_dynprop.data, _x.cluster_general.cluster_rcs.data, _x.cluster_quality.cluster_distlong_rms.data, _x.cluster_quality.cluster_distlat_rms.data, _x.cluster_quality.cluster_vrellong_rms.data, _x.cluster_quality.cluster_vrellat_rms.data,) = _get_struct_i4di5d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cluster_quality.cluster_pdh0.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cluster_quality.cluster_pdh0.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cluster_quality.cluster_invalidstate.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cluster_quality.cluster_invalidstate.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cluster_quality.cluster_ambigstate.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cluster_quality.cluster_ambigstate.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i4di5d().pack(_x.cluster_id.data, _x.cluster_general.cluster_distlong.data, _x.cluster_general.cluster_distlat.data, _x.cluster_general.cluster_vrellong.data, _x.cluster_general.cluster_vrellat.data, _x.cluster_general.cluster_dynprop.data, _x.cluster_general.cluster_rcs.data, _x.cluster_quality.cluster_distlong_rms.data, _x.cluster_quality.cluster_distlat_rms.data, _x.cluster_quality.cluster_vrellong_rms.data, _x.cluster_quality.cluster_vrellat_rms.data))
      _x = self.cluster_quality.cluster_pdh0.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cluster_quality.cluster_invalidstate.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cluster_quality.cluster_ambigstate.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cluster_id is None:
        self.cluster_id = std_msgs.msg.Int32()
      if self.cluster_general is None:
        self.cluster_general = radar_conti.msg.ClusterGeneral()
      if self.cluster_quality is None:
        self.cluster_quality = radar_conti.msg.ClusterQuality()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.cluster_id.data, _x.cluster_general.cluster_distlong.data, _x.cluster_general.cluster_distlat.data, _x.cluster_general.cluster_vrellong.data, _x.cluster_general.cluster_vrellat.data, _x.cluster_general.cluster_dynprop.data, _x.cluster_general.cluster_rcs.data, _x.cluster_quality.cluster_distlong_rms.data, _x.cluster_quality.cluster_distlat_rms.data, _x.cluster_quality.cluster_vrellong_rms.data, _x.cluster_quality.cluster_vrellat_rms.data,) = _get_struct_i4di5d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cluster_quality.cluster_pdh0.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cluster_quality.cluster_pdh0.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cluster_quality.cluster_invalidstate.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cluster_quality.cluster_invalidstate.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cluster_quality.cluster_ambigstate.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cluster_quality.cluster_ambigstate.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i4di5d = None
def _get_struct_i4di5d():
    global _struct_i4di5d
    if _struct_i4di5d is None:
        _struct_i4di5d = struct.Struct("<i4di5d")
    return _struct_i4di5d
