# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_conti/ClusterList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import radar_conti.msg
import std_msgs.msg

class ClusterList(genpy.Message):
  _md5sum = "f224f52f8435f121b949e6b05d35dc26"
  _type = "radar_conti/ClusterList"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
std_msgs/Int32 cluster_count
Cluster[] clusters
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: std_msgs/Int32
int32 data
================================================================================
MSG: radar_conti/Cluster
std_msgs/Int32 cluster_id
ClusterGeneral cluster_general
ClusterQuality cluster_quality
================================================================================
MSG: radar_conti/ClusterGeneral
#  ------------------------------------------------------------------------
#
#  Name:       Cluster_1_General
#  Id:         0x701
#  Length:     8 bytes
#  Cycle time: 0 ms
#  Senders:    ARS_ISF
#  Layout:
#
#                          Bit
#
#             7   6   5   4   3   2   1   0
#           +---+---+---+---+---+---+---+---+
#         0 |<-----------------------------x|
#           +---+---+---+---+---+---+---+---+
#                                         +-- Cluster_ID
#           +---+---+---+---+---+---+---+---+
#         1 |<------------------------------|
#           +---+---+---+---+---+---+---+---+
#         2 |------------------x|   |<------|
#           +---+---+---+---+---+---+---+---+
#                             +-- Cluster_DistLong
#           +---+---+---+---+---+---+---+---+
#         3 |------------------------------x|
#     B     +---+---+---+---+---+---+---+---+
#     y                                   +-- Cluster_DistLat
#     t     +---+---+---+---+---+---+---+---+
#     e   4 |<------------------------------|
#           +---+---+---+---+---+---+---+---+
#         5 |------x|<----------------------|
#           +---+---+---+---+---+---+---+---+
#                 +-- Cluster_VrelLong
#           +---+---+---+---+---+---+---+---+
#         6 |----------x|   |   |<---------x|
#           +---+---+---+---+---+---+---+---+
#                     |                   +-- Cluster_DynProp
#                     +-- Cluster_VrelLat
#           +---+---+---+---+---+---+---+---+
#         7 |<-----------------------------x|
#           +---+---+---+---+---+---+---+---+
#                                         +-- Cluster_RCS
#
#  Signal tree:
#
#    -- {root}
#       +-- Cluster_ID
#       +-- Cluster_DistLong
#       +-- Cluster_DistLat
#       +-- Cluster_VrelLong
#       +-- Cluster_VrelLat
#       +-- Cluster_DynProp
#       +-- Cluster_RCS
#
#  ------------------------------------------------------------------------
std_msgs/Float64 cluster_distlong
std_msgs/Float64 cluster_distlat
std_msgs/Float64 cluster_vrellong
std_msgs/Float64 cluster_vrellat
std_msgs/Int32   cluster_dynprop
std_msgs/Float64 cluster_rcs
================================================================================
MSG: std_msgs/Float64
float64 data
================================================================================
MSG: radar_conti/ClusterQuality
#  ------------------------------------------------------------------------
#
#  Name:       Cluster_2_Quality
#  Id:         0x702
#  Length:     5 bytes
#  Cycle time: 0 ms
#  Senders:    ARS_ISF
#  Layout:
#
#                          Bit
#
#             7   6   5   4   3   2   1   0
#           +---+---+---+---+---+---+---+---+
#         0 |<-----------------------------x|
#           +---+---+---+---+---+---+---+---+
#                                         +-- Cluster_ID
#           +---+---+---+---+---+---+---+---+
#         1 |<-----------------x|<----------|
#           +---+---+---+---+---+---+---+---+
#                             +-- Cluster_DistLong_rms
#           +---+---+---+---+---+---+---+---+
#     B   2 |------x|<-----------------x|<--|
#     y     +---+---+---+---+---+---+---+---+
#     t           |                   +-- Cluster_VrelLong_rms
#     e           +-- Cluster_DistLat_rms
#           +---+---+---+---+---+---+---+---+
#         3 |--------------x|   |<---------x|
#           +---+---+---+---+---+---+---+---+
#                         |               +-- Cluster_PdH0
#                         +-- Cluster_VrelLat_rms
#           +---+---+---+---+---+---+---+---+
#         4 |<-----------------x|<---------x|
#           +---+---+---+---+---+---+---+---+
#                             |           +-- Cluster_AmbigState
#                             +-- Cluster_InvalidState
#
#  Signal tree:
#
#    -- {root}
#       +-- Cluster_ID
#       +-- Cluster_DistLong_rms
#       +-- Cluster_DistLat_rms
#       +-- Cluster_VrelLong_rms
#       +-- Cluster_VrelLat_rms
#       +-- Cluster_PdH0
#       +-- Cluster_InvalidState
#       +-- Cluster_AmbigState
#
#  ------------------------------------------------------------------------
#
std_msgs/Float64 cluster_distlong_rms
std_msgs/Float64 cluster_distlat_rms
std_msgs/Float64 cluster_vrellong_rms
std_msgs/Float64 cluster_vrellat_rms
std_msgs/String cluster_pdh0
std_msgs/String cluster_invalidstate
std_msgs/String cluster_ambigstate
================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['header','cluster_count','clusters']
  _slot_types = ['std_msgs/Header','std_msgs/Int32','radar_conti/Cluster[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,cluster_count,clusters

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ClusterList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cluster_count is None:
        self.cluster_count = std_msgs.msg.Int32()
      if self.clusters is None:
        self.clusters = []
    else:
      self.header = std_msgs.msg.Header()
      self.cluster_count = std_msgs.msg.Int32()
      self.clusters = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cluster_count.data
      buff.write(_get_struct_i().pack(_x))
      length = len(self.clusters)
      buff.write(_struct_I.pack(length))
      for val1 in self.clusters:
        _v1 = val1.cluster_id
        _x = _v1.data
        buff.write(_get_struct_i().pack(_x))
        _v2 = val1.cluster_general
        _v3 = _v2.cluster_distlong
        _x = _v3.data
        buff.write(_get_struct_d().pack(_x))
        _v4 = _v2.cluster_distlat
        _x = _v4.data
        buff.write(_get_struct_d().pack(_x))
        _v5 = _v2.cluster_vrellong
        _x = _v5.data
        buff.write(_get_struct_d().pack(_x))
        _v6 = _v2.cluster_vrellat
        _x = _v6.data
        buff.write(_get_struct_d().pack(_x))
        _v7 = _v2.cluster_dynprop
        _x = _v7.data
        buff.write(_get_struct_i().pack(_x))
        _v8 = _v2.cluster_rcs
        _x = _v8.data
        buff.write(_get_struct_d().pack(_x))
        _v9 = val1.cluster_quality
        _v10 = _v9.cluster_distlong_rms
        _x = _v10.data
        buff.write(_get_struct_d().pack(_x))
        _v11 = _v9.cluster_distlat_rms
        _x = _v11.data
        buff.write(_get_struct_d().pack(_x))
        _v12 = _v9.cluster_vrellong_rms
        _x = _v12.data
        buff.write(_get_struct_d().pack(_x))
        _v13 = _v9.cluster_vrellat_rms
        _x = _v13.data
        buff.write(_get_struct_d().pack(_x))
        _v14 = _v9.cluster_pdh0
        _x = _v14.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v15 = _v9.cluster_invalidstate
        _x = _v15.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v16 = _v9.cluster_ambigstate
        _x = _v16.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cluster_count is None:
        self.cluster_count = std_msgs.msg.Int32()
      if self.clusters is None:
        self.clusters = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.cluster_count.data,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.clusters = []
      for i in range(0, length):
        val1 = radar_conti.msg.Cluster()
        _v17 = val1.cluster_id
        start = end
        end += 4
        (_v17.data,) = _get_struct_i().unpack(str[start:end])
        _v18 = val1.cluster_general
        _v19 = _v18.cluster_distlong
        start = end
        end += 8
        (_v19.data,) = _get_struct_d().unpack(str[start:end])
        _v20 = _v18.cluster_distlat
        start = end
        end += 8
        (_v20.data,) = _get_struct_d().unpack(str[start:end])
        _v21 = _v18.cluster_vrellong
        start = end
        end += 8
        (_v21.data,) = _get_struct_d().unpack(str[start:end])
        _v22 = _v18.cluster_vrellat
        start = end
        end += 8
        (_v22.data,) = _get_struct_d().unpack(str[start:end])
        _v23 = _v18.cluster_dynprop
        start = end
        end += 4
        (_v23.data,) = _get_struct_i().unpack(str[start:end])
        _v24 = _v18.cluster_rcs
        start = end
        end += 8
        (_v24.data,) = _get_struct_d().unpack(str[start:end])
        _v25 = val1.cluster_quality
        _v26 = _v25.cluster_distlong_rms
        start = end
        end += 8
        (_v26.data,) = _get_struct_d().unpack(str[start:end])
        _v27 = _v25.cluster_distlat_rms
        start = end
        end += 8
        (_v27.data,) = _get_struct_d().unpack(str[start:end])
        _v28 = _v25.cluster_vrellong_rms
        start = end
        end += 8
        (_v28.data,) = _get_struct_d().unpack(str[start:end])
        _v29 = _v25.cluster_vrellat_rms
        start = end
        end += 8
        (_v29.data,) = _get_struct_d().unpack(str[start:end])
        _v30 = _v25.cluster_pdh0
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v30.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v30.data = str[start:end]
        _v31 = _v25.cluster_invalidstate
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v31.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v31.data = str[start:end]
        _v32 = _v25.cluster_ambigstate
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v32.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v32.data = str[start:end]
        self.clusters.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.cluster_count.data
      buff.write(_get_struct_i().pack(_x))
      length = len(self.clusters)
      buff.write(_struct_I.pack(length))
      for val1 in self.clusters:
        _v33 = val1.cluster_id
        _x = _v33.data
        buff.write(_get_struct_i().pack(_x))
        _v34 = val1.cluster_general
        _v35 = _v34.cluster_distlong
        _x = _v35.data
        buff.write(_get_struct_d().pack(_x))
        _v36 = _v34.cluster_distlat
        _x = _v36.data
        buff.write(_get_struct_d().pack(_x))
        _v37 = _v34.cluster_vrellong
        _x = _v37.data
        buff.write(_get_struct_d().pack(_x))
        _v38 = _v34.cluster_vrellat
        _x = _v38.data
        buff.write(_get_struct_d().pack(_x))
        _v39 = _v34.cluster_dynprop
        _x = _v39.data
        buff.write(_get_struct_i().pack(_x))
        _v40 = _v34.cluster_rcs
        _x = _v40.data
        buff.write(_get_struct_d().pack(_x))
        _v41 = val1.cluster_quality
        _v42 = _v41.cluster_distlong_rms
        _x = _v42.data
        buff.write(_get_struct_d().pack(_x))
        _v43 = _v41.cluster_distlat_rms
        _x = _v43.data
        buff.write(_get_struct_d().pack(_x))
        _v44 = _v41.cluster_vrellong_rms
        _x = _v44.data
        buff.write(_get_struct_d().pack(_x))
        _v45 = _v41.cluster_vrellat_rms
        _x = _v45.data
        buff.write(_get_struct_d().pack(_x))
        _v46 = _v41.cluster_pdh0
        _x = _v46.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v47 = _v41.cluster_invalidstate
        _x = _v47.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v48 = _v41.cluster_ambigstate
        _x = _v48.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cluster_count is None:
        self.cluster_count = std_msgs.msg.Int32()
      if self.clusters is None:
        self.clusters = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.cluster_count.data,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.clusters = []
      for i in range(0, length):
        val1 = radar_conti.msg.Cluster()
        _v49 = val1.cluster_id
        start = end
        end += 4
        (_v49.data,) = _get_struct_i().unpack(str[start:end])
        _v50 = val1.cluster_general
        _v51 = _v50.cluster_distlong
        start = end
        end += 8
        (_v51.data,) = _get_struct_d().unpack(str[start:end])
        _v52 = _v50.cluster_distlat
        start = end
        end += 8
        (_v52.data,) = _get_struct_d().unpack(str[start:end])
        _v53 = _v50.cluster_vrellong
        start = end
        end += 8
        (_v53.data,) = _get_struct_d().unpack(str[start:end])
        _v54 = _v50.cluster_vrellat
        start = end
        end += 8
        (_v54.data,) = _get_struct_d().unpack(str[start:end])
        _v55 = _v50.cluster_dynprop
        start = end
        end += 4
        (_v55.data,) = _get_struct_i().unpack(str[start:end])
        _v56 = _v50.cluster_rcs
        start = end
        end += 8
        (_v56.data,) = _get_struct_d().unpack(str[start:end])
        _v57 = val1.cluster_quality
        _v58 = _v57.cluster_distlong_rms
        start = end
        end += 8
        (_v58.data,) = _get_struct_d().unpack(str[start:end])
        _v59 = _v57.cluster_distlat_rms
        start = end
        end += 8
        (_v59.data,) = _get_struct_d().unpack(str[start:end])
        _v60 = _v57.cluster_vrellong_rms
        start = end
        end += 8
        (_v60.data,) = _get_struct_d().unpack(str[start:end])
        _v61 = _v57.cluster_vrellat_rms
        start = end
        end += 8
        (_v61.data,) = _get_struct_d().unpack(str[start:end])
        _v62 = _v57.cluster_pdh0
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v62.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v62.data = str[start:end]
        _v63 = _v57.cluster_invalidstate
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v63.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v63.data = str[start:end]
        _v64 = _v57.cluster_ambigstate
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v64.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v64.data = str[start:end]
        self.clusters.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
