# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_conti/VersionID.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class VersionID(genpy.Message):
  _md5sum = "ea1b12f3e20711755dbdd58cbc0c1b78"
  _type = "radar_conti/VersionID"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """#  ------------------------------------------------------------------------
#
#  Name:       VersionID
#  Id:         0x700
#  Length:     4 bytes
#  Cycle time: 0 ms
#  Senders:    ARS_ISF
#  Layout:
#
#                          Bit
#
#             7   6   5   4   3   2   1   0
#           +---+---+---+---+---+---+---+---+
#         0 |<-----------------------------x|
#           +---+---+---+---+---+---+---+---+
#                                         +-- Version_MajorRelease
#           +---+---+---+---+---+---+---+---+
#         1 |<-----------------------------x|
#     B     +---+---+---+---+---+---+---+---+
#     y                                   +-- Version_MinorRelease
#     t     +---+---+---+---+---+---+---+---+
#     e   2 |<-----------------------------x|
#           +---+---+---+---+---+---+---+---+
#                                         +-- Version_PatchLevel
#           +---+---+---+---+---+---+---+---+
#         3 |   |   |   |   |   |   |<-x|<-x|
#           +---+---+---+---+---+---+---+---+
#                                     |   +-- Version_CountryCode
#                                     +-- Version_ExtendedRange
#
#  Signal tree:
#
#    -- {root}
#       +-- Version_MajorRelease
#       +-- Version_MinorRelease
#       +-- Version_PatchLevel
#       +-- Version_ExtendedRange
#       +-- Version_CountryCode
#
#  ------------------------------------------------------------------------
std_msgs/Header header
std_msgs/Int32 version_majorrelease
std_msgs/Int32 version_minorrelease
std_msgs/Int32 version_patchlevel
std_msgs/String version_extendedrange
std_msgs/String version_countrycode
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: std_msgs/Int32
int32 data
================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['header','version_majorrelease','version_minorrelease','version_patchlevel','version_extendedrange','version_countrycode']
  _slot_types = ['std_msgs/Header','std_msgs/Int32','std_msgs/Int32','std_msgs/Int32','std_msgs/String','std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,version_majorrelease,version_minorrelease,version_patchlevel,version_extendedrange,version_countrycode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VersionID, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.version_majorrelease is None:
        self.version_majorrelease = std_msgs.msg.Int32()
      if self.version_minorrelease is None:
        self.version_minorrelease = std_msgs.msg.Int32()
      if self.version_patchlevel is None:
        self.version_patchlevel = std_msgs.msg.Int32()
      if self.version_extendedrange is None:
        self.version_extendedrange = std_msgs.msg.String()
      if self.version_countrycode is None:
        self.version_countrycode = std_msgs.msg.String()
    else:
      self.header = std_msgs.msg.Header()
      self.version_majorrelease = std_msgs.msg.Int32()
      self.version_minorrelease = std_msgs.msg.Int32()
      self.version_patchlevel = std_msgs.msg.Int32()
      self.version_extendedrange = std_msgs.msg.String()
      self.version_countrycode = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3i().pack(_x.version_majorrelease.data, _x.version_minorrelease.data, _x.version_patchlevel.data))
      _x = self.version_extendedrange.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.version_countrycode.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.version_majorrelease is None:
        self.version_majorrelease = std_msgs.msg.Int32()
      if self.version_minorrelease is None:
        self.version_minorrelease = std_msgs.msg.Int32()
      if self.version_patchlevel is None:
        self.version_patchlevel = std_msgs.msg.Int32()
      if self.version_extendedrange is None:
        self.version_extendedrange = std_msgs.msg.String()
      if self.version_countrycode is None:
        self.version_countrycode = std_msgs.msg.String()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.version_majorrelease.data, _x.version_minorrelease.data, _x.version_patchlevel.data,) = _get_struct_3i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.version_extendedrange.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.version_extendedrange.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.version_countrycode.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.version_countrycode.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3i().pack(_x.version_majorrelease.data, _x.version_minorrelease.data, _x.version_patchlevel.data))
      _x = self.version_extendedrange.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.version_countrycode.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.version_majorrelease is None:
        self.version_majorrelease = std_msgs.msg.Int32()
      if self.version_minorrelease is None:
        self.version_minorrelease = std_msgs.msg.Int32()
      if self.version_patchlevel is None:
        self.version_patchlevel = std_msgs.msg.Int32()
      if self.version_extendedrange is None:
        self.version_extendedrange = std_msgs.msg.String()
      if self.version_countrycode is None:
        self.version_countrycode = std_msgs.msg.String()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.version_majorrelease.data, _x.version_minorrelease.data, _x.version_patchlevel.data,) = _get_struct_3i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.version_extendedrange.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.version_extendedrange.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.version_countrycode.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.version_countrycode.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3i = None
def _get_struct_3i():
    global _struct_3i
    if _struct_3i is None:
        _struct_3i = struct.Struct("<3i")
    return _struct_3i
