// Generated by gencpp from file pro_can/control_data.msg
// DO NOT EDIT!


#ifndef PRO_CAN_MESSAGE_CONTROL_DATA_H
#define PRO_CAN_MESSAGE_CONTROL_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pro_can
{
template <class ContainerAllocator>
struct control_data_
{
  typedef control_data_<ContainerAllocator> Type;

  control_data_()
    : header()
    , acc_command_value(0.0)
    , brake_command_value(0.0)
    , steering_wheel_command_value(0.0)  {
    }
  control_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acc_command_value(0.0)
    , brake_command_value(0.0)
    , steering_wheel_command_value(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _acc_command_value_type;
  _acc_command_value_type acc_command_value;

   typedef double _brake_command_value_type;
  _brake_command_value_type brake_command_value;

   typedef double _steering_wheel_command_value_type;
  _steering_wheel_command_value_type steering_wheel_command_value;





  typedef boost::shared_ptr< ::pro_can::control_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pro_can::control_data_<ContainerAllocator> const> ConstPtr;

}; // struct control_data_

typedef ::pro_can::control_data_<std::allocator<void> > control_data;

typedef boost::shared_ptr< ::pro_can::control_data > control_dataPtr;
typedef boost::shared_ptr< ::pro_can::control_data const> control_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pro_can::control_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pro_can::control_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pro_can::control_data_<ContainerAllocator1> & lhs, const ::pro_can::control_data_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.acc_command_value == rhs.acc_command_value &&
    lhs.brake_command_value == rhs.brake_command_value &&
    lhs.steering_wheel_command_value == rhs.steering_wheel_command_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pro_can::control_data_<ContainerAllocator1> & lhs, const ::pro_can::control_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pro_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pro_can::control_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pro_can::control_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pro_can::control_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pro_can::control_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pro_can::control_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pro_can::control_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pro_can::control_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d09a1efa4e00097fb79b2c455901250c";
  }

  static const char* value(const ::pro_can::control_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd09a1efa4e00097fULL;
  static const uint64_t static_value2 = 0xb79b2c455901250cULL;
};

template<class ContainerAllocator>
struct DataType< ::pro_can::control_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pro_can/control_data";
  }

  static const char* value(const ::pro_can::control_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pro_can::control_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# [TEMP SIM] control_data — longitudinal actuator command (mirrors real pro_can/control_data).\n"
"# Fields used by acc_aeb_node:\n"
"#   header.stamp              — publish timestamp\n"
"#   acc_command_value         — motor torque (Nm); positive = drive\n"
"#   brake_command_value       — braking demand in G (0–0.6)\n"
"#   steering_wheel_command_value — always 0.0 from the ACC/AEB node\n"
"std_msgs/Header header\n"
"float64 acc_command_value\n"
"float64 brake_command_value\n"
"float64 steering_wheel_command_value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pro_can::control_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pro_can::control_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acc_command_value);
      stream.next(m.brake_command_value);
      stream.next(m.steering_wheel_command_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pro_can::control_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pro_can::control_data_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acc_command_value: ";
    Printer<double>::stream(s, indent + "  ", v.acc_command_value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "brake_command_value: ";
    Printer<double>::stream(s, indent + "  ", v.brake_command_value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_wheel_command_value: ";
    Printer<double>::stream(s, indent + "  ", v.steering_wheel_command_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRO_CAN_MESSAGE_CONTROL_DATA_H
