// Generated by gencpp from file pro_can/VCU.msg
// DO NOT EDIT!


#ifndef PRO_CAN_MESSAGE_VCU_H
#define PRO_CAN_MESSAGE_VCU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pro_can
{
template <class ContainerAllocator>
struct VCU_
{
  typedef VCU_<ContainerAllocator> Type;

  VCU_()
    : MotorVelocity(0.0)  {
    }
  VCU_(const ContainerAllocator& _alloc)
    : MotorVelocity(0.0)  {
  (void)_alloc;
    }



   typedef float _MotorVelocity_type;
  _MotorVelocity_type MotorVelocity;





  typedef boost::shared_ptr< ::pro_can::VCU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pro_can::VCU_<ContainerAllocator> const> ConstPtr;

}; // struct VCU_

typedef ::pro_can::VCU_<std::allocator<void> > VCU;

typedef boost::shared_ptr< ::pro_can::VCU > VCUPtr;
typedef boost::shared_ptr< ::pro_can::VCU const> VCUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pro_can::VCU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pro_can::VCU_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pro_can::VCU_<ContainerAllocator1> & lhs, const ::pro_can::VCU_<ContainerAllocator2> & rhs)
{
  return lhs.MotorVelocity == rhs.MotorVelocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pro_can::VCU_<ContainerAllocator1> & lhs, const ::pro_can::VCU_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pro_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pro_can::VCU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pro_can::VCU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pro_can::VCU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pro_can::VCU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pro_can::VCU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pro_can::VCU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pro_can::VCU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bad68293825d700d1b4f59a02856c41b";
  }

  static const char* value(const ::pro_can::VCU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbad68293825d700dULL;
  static const uint64_t static_value2 = 0x1b4f59a02856c41bULL;
};

template<class ContainerAllocator>
struct DataType< ::pro_can::VCU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pro_can/VCU";
  }

  static const char* value(const ::pro_can::VCU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pro_can::VCU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# [TEMP SIM] VCU — ego-speed message stub (mirrors real pro_can/VCU).\n"
"# Field used by acc_aeb_node: MotorVelocity (km/h), cast to double.\n"
"float32 MotorVelocity\n"
;
  }

  static const char* value(const ::pro_can::VCU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pro_can::VCU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.MotorVelocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VCU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pro_can::VCU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pro_can::VCU_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "MotorVelocity: ";
    Printer<float>::stream(s, indent + "  ", v.MotorVelocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRO_CAN_MESSAGE_VCU_H
